name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is
      placeholder: When I try to encode..., I expect..., but instead...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import ToonFormat
        2. Call encode() with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (including error messages)
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: swift-toon Version
      description: Which version of swift-toon are you using?
      options:
        - 0.2.0 (latest)
        - 0.1.0
        - Other (please specify in Additional Context)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide:
        - Swift version
        - Xcode version (if applicable)
        - Platform (iOS, macOS, etc.)
        - Operating system
      placeholder: |
        - Swift 6.0
        - Xcode 16.0
        - macOS 15.0
        - iOS 17.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (optional)
