name: SPEC Compliance Issue
description: Report a deviation from the TOON specification
labels: ["spec-compliance"]
body:
  - type: markdown
    attributes:
      value: |
        Report an issue where TOONEncoder doesn't comply with the official TOON spec.

  - type: input
    id: spec-version
    attributes:
      label: SPEC Version
      description: Which version of the TOON spec does this relate to?
      placeholder: v3.0
    validations:
      required: true

  - type: input
    id: spec-section
    attributes:
      label: SPEC Section
      description: Which section of SPEC.md is affected?
      placeholder: "Section 7.1: Escaping (Encoding and Decoding)"
    validations:
      required: true

  - type: textarea
    id: spec-requirement
    attributes:
      label: SPEC Requirement
      description: What does the spec require?
      placeholder: According to SPEC.md, the encoder should...
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What does TOONEncoder currently do?
      placeholder: Currently, TOONEncoder...
    validations:
      required: true

  - type: textarea
    id: test-case
    attributes:
      label: Test Case
      description: Provide a test case that demonstrates the issue
      placeholder: |
        ```swift
        import TOONEncoder
        let encoder = TOONEncoder()
        let result = try encoder.encode(...)
        // Expected: ...
        // Actual: ...
        ```
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
